import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from '../context/AuthContext';
export default function Reports() {
    const { halls, payments, reservations } = useAuth();
    const totalHalls = halls.length;
    const occupiedHalls = halls.filter(h => h.status === 'Occupied').length;
    const avgOccupancy = totalHalls > 0 ? Math.round((occupiedHalls / totalHalls) * 100) : 0;
    const totalRevenue = payments.reduce((acc, p) => acc + p.amount, 0);
    const pendingRevenue = reservations.filter(r => r.paymentStatus === 'Pending').reduce((acc, r) => acc + r.amount, 0);
    return (_jsxs("div", { children: [_jsxs("div", { className: "page-header", children: [_jsx("h1", { className: "page-title", children: "Analytics & Hall Reports" }), _jsx("button", { className: "btn-secondary", children: "Export PDF Report" })] }), _jsxs("div", { style: { display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '24px' }, children: [_jsxs("div", { className: "card glass-card", children: [_jsx("h3", { children: "Utilization Metrics" }), _jsxs("div", { style: { marginTop: '24px' }, children: [_jsxs("div", { className: "form-group", children: [_jsx("label", { children: "Hall Occupancy" }), _jsx("div", { style: { height: '20px', backgroundColor: '#eee', borderRadius: '10px', overflow: 'hidden' }, children: _jsx("div", { style: { height: '100%', width: `${avgOccupancy}%`, backgroundColor: 'var(--primary)' } }) }), _jsxs("p", { style: { marginTop: '8px', fontWeight: 600 }, children: [avgOccupancy, "% across ", totalHalls, " halls"] })] }), _jsxs("div", { style: { marginTop: '32px' }, children: [_jsx("h4", { style: { color: 'var(--text-muted)', fontSize: '0.8rem' }, children: "Total Realized Revenue" }), _jsxs("p", { style: { fontSize: '1.8rem', fontWeight: 700 }, children: ["\u20B9", totalRevenue.toLocaleString()] })] }), _jsxs("div", { style: { marginTop: '16px' }, children: [_jsx("h4", { style: { color: 'var(--text-muted)', fontSize: '0.8rem' }, children: "Pending Payments" }), _jsxs("p", { style: { fontSize: '1.5rem', fontWeight: 600, color: '#dc3545' }, children: ["\u20B9", pendingRevenue.toLocaleString()] })] })] })] }), _jsxs("div", { className: "card glass-card", children: [_jsx("h3", { children: "Venue Performance Breakdown" }), _jsx("div", { style: { marginTop: '16px' }, children: _jsxs("table", { children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Hall Name" }), _jsx("th", { children: "Bookings" }), _jsx("th", { children: "Revenue" }), _jsx("th", { children: "Utilization" })] }) }), _jsx("tbody", { children: halls.map(hall => {
                                                const hallBookings = reservations.filter(r => r.hallId === hall.id);
                                                const hallRevenue = hallBookings.reduce((acc, r) => acc + (r.paymentStatus === 'Paid' ? r.amount : 0), 0);
                                                const bookingCount = hallBookings.length;
                                                return (_jsxs("tr", { children: [_jsx("td", { children: hall.name }), _jsx("td", { children: bookingCount }), _jsxs("td", { children: ["\u20B9", hallRevenue.toLocaleString()] }), _jsx("td", { children: _jsx("span", { style: { color: hall.status === 'Occupied' ? 'var(--primary)' : 'inherit' }, children: hall.status }) })] }, hall.id));
                                            }) })] }) })] })] })] }));
}
